# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Call It Magic' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.3'

pod 'PureLayout'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SnapKit', '~> 0.12.0'

end

target 'Call It MagicTests' do

end

